#!/usr/bin/env python3
"""
Generate Terraform code to apply cost optimizations
"""

import json
import os
from datetime import datetime
from rich.console import Console

console = Console()

class TerraformFixGenerator:
    def __init__(self, findings_file='findings.json'):
        with open(findings_file) as f:
            self.findings = json.load(f)
        self.terraform_code = []

    def generate_header(self):
        return f"""# Auto-generated by AWS Cost Optimizer
# Generated: {datetime.now().isoformat()}
# WARNING: Review this code carefully before applying!

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "us-east-1"
}}

"""

    def generate_ebs_deletion(self, finding):
        volume_id = finding['id']
        return f"""
# Delete unattached EBS volume: {volume_id}
# Estimated savings: ${finding['monthly_cost']}/month
resource "aws_ebs_volume_delete" "{volume_id}" {{
  volume_id = "{volume_id}"

  # Safety: Set to true to actually delete
  # Change to false to preview only
  force_delete = false

  lifecycle {{
    create_before_destroy = true
  }}
}}
"""

    def generate_eip_release(self, finding):
        allocation_id = finding['id']
        return f"""
# Release unassociated Elastic IP: {allocation_id}
# Estimated savings: ${finding['monthly_cost']}/month
resource "aws_eip_association_release" "{allocation_id.replace('-', '_')}" {{
  allocation_id = "{allocation_id}"

  # Safety: Set to true to actually release
  # Change to false to preview only
  public_ip = "{allocation_id}"

  lifecycle {{
    create_before_destroy = true
  }}
}}
"""

    def generate_snapshot_deletion(self, finding):
        snapshot_id = finding['id']
        return f"""
# Delete old snapshot: {snapshot_id}
# Estimated savings: ${finding['monthly_cost']}/month
resource "aws_ebs_snapshot_delete" "{snapshot_id}" {{
  snapshot_id = "{snapshot_id}"

  # Safety: Set to true to actually delete
  # Change to false to preview only
  force_delete = false

  lifecycle {{
    create_before_destroy = true
  }}
}}
"""

    def generate_instance_stop(self, finding):
        instance_id = finding['id']
        return f"""
# Stop idle EC2 instance: {instance_id}
# Issue: {finding['issue']}
# Estimated savings: ${finding['monthly_cost']}/month

# Note: This uses null_resource to stop instance
# Review carefully before applying
resource "null_resource" "stop_{instance_id.replace('-', '_')}" {{
  provisioner "local-exec" {{
    command = "aws ec2 stop-instances --instance-ids {instance_id} --region us-east-1"
  }}

  # Triggers on finding timestamp to allow re-runs
  triggers = {{
    timestamp = "{finding['timestamp']}"
  }}
}}
"""

    def generate(self, output_file='fixes.tf'):
        console.print("[cyan]🔨 Generating Terraform fixes...[/cyan]")

        self.terraform_code.append(self.generate_header())

        ebs_count = 0
        eip_count = 0
        snapshot_count = 0
        instance_count = 0

        for finding in self.findings:
            if finding['type'] == 'EBS Volume':
                self.terraform_code.append(self.generate_ebs_deletion(finding))
                ebs_count += 1
            elif finding['type'] == 'Elastic IP':
                self.terraform_code.append(self.generate_eip_release(finding))
                eip_count += 1
            elif finding['type'] == 'EBS Snapshot':
                self.terraform_code.append(self.generate_snapshot_deletion(finding))
                snapshot_count += 1
            elif finding['type'] == 'EC2 Instance':
                self.terraform_code.append(self.generate_instance_stop(finding))
                instance_count += 1

        with open(output_file, 'w') as f:
            f.write(''.join(self.terraform_code))

        console.print(f"\n[green]✅ Terraform code generated: {output_file}[/green]")
        console.print(f"   - {ebs_count} EBS volumes to delete")
        console.print(f"   - {eip_count} Elastic IPs to release")
        console.print(f"   - {snapshot_count} old snapshots to delete")
        console.print(f"   - {instance_count} instances to stop")
        console.print("\n[cyan]Next steps:[/cyan]")
        console.print("  1. Review the generated fixes.tf file")
        console.print("  2. Run: terraform init")
        console.print("  3. Run: terraform plan  (REVIEW THIS CAREFULLY)")
        console.print("  4. Run: terraform apply  (when ready)")
        console.print("\n[yellow]⚠️  SAFETY NOTE:[/yellow]")
        console.print("   - All force_delete flags default to false")
        console.print("   - Change to true only after review")
        console.print("   - Test in a non-production environment first")


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Generate Terraform fixes for cost optimization')
    parser.add_argument('--input', default='findings.json', help='Input findings JSON file')
    parser.add_argument('--output', default='fixes.tf', help='Output Terraform file')
    args = parser.parse_args()

    if not os.path.exists(args.input):
        console.print(f"[red]❌ Error: {args.input} not found. Run scan.py first.[/red]")
        return

    generator = TerraformFixGenerator(args.input)
    generator.generate(args.output)


if __name__ == '__main__':
    main()